# Generated by Django 5.1.7 on 2025-03-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_airbnblisting_image_urls_airbnblisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbnblisting',
            name='reviews',
            field=models.CharField(blank=True, default='1', max_length=255),
        ),
    ]
