# Generated by Django 5.1.7 on 2025-03-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_airbnblisting_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbnblisting',
            name='amenities',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
